CREATE TABLE IF NOT EXISTS buyer(
  id SERIAL PRIMARY KEY ,
  name CHARACTER VARYING(15) NOT NULL ,
  surname CHARACTER VARYING(30) NOT NULL,
  gender CHARACTER VARYING(8) NOT NULL,
  cardId BIGINT NULL
);