CREATE TABLE product(
  id BIGINT PRIMARY KEY ,
  shopId BIGINT REFERENCES shop(id),
  name CHARACTER VARYING(15) NOT NULL,
  cost MONEY NOT NULL ,
  date DATE NOT NULL ,
  weight DOUBLE PRECISION NOT NULL
);
