CREATE TABLE IF NOT EXISTS product(
  id SERIAL PRIMARY KEY ,
  shopId BIGINT REFERENCES shop(id),
  name CHARACTER VARYING(15) NOT NULL,
  cost CHARACTER VARYING(15) NOT NULL ,
  date CHARACTER VARYING(15) NOT NULL ,
  weight DOUBLE PRECISION NOT NULL
);
