CREATE TABLE IF NOT EXISTS shopCheck(
  id SERIAL PRIMARY KEY ,
  buyerId BIGINT references buyer(id),
  operationType CHARACTER VARYING(10) NOT NULL ,
  time CHARACTER VARYING(10),
  date CHARACTER VARYING(20)
);
